---
genPolicy: "Create"
openAPISpec: "http://localhost:8080/v2/api-docs"
generators:
- type: "no_params"
  assertions:
  - "@StatusCode == 200"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "anonymous_invalid"
  assertions:
  - "@StatusCode != 200"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "auth_invalid"
  assertions:
  - "@StatusCode != 200"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "DDOS"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags: null
  severity: null
  database: null
  inactive: false
  matches:
  - name: "pageSize, page_size, maxResults, max_results"
    value: null
    methods: null
    denyRoles: null
    allowRoles: null
    pathPatterns: null
    resourceSamples: null
    queryParams: null
    bodyProperties: null
- type: "XSS_Injection"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "sql_injection_timebound"
  assertions:
  - "@ResponseTime < 7000"
  - "@StatusCode != 404"
  tags: null
  severity: null
  database:
    name: "MySQL"
    version: "5.7"
  inactive: false
  matches: []
- type: "log_Forging"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "invalid_datatype"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "special_chars "
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "null_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "empty_value"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "negative_number"
  assertions:
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
- type: "create"
  assertions:
  - "@StatusCode != 200"
  - "@StatusCode != 401"
  - "@StatusCode != 404"
  - "@StatusCode != 500"
  tags: null
  severity: null
  database: null
  inactive: false
  matches: []
